// Generated by CoffeeScript 1.12.4
var emptyFunction, isBenchmark, now;

emptyFunction = require("emptyFunction");

now = require("performance-now");

isBenchmark = function(spec) {
  return spec.description === "has a benchmark";
};

module.exports = {
  startAll: function() {
    this.specsPassed = 0;
    this.startTime = now();
    log.pushIndent(2);
    return log.moat(1);
  },
  startSome: function(suite) {
    log.moat(1);
    log.white(suite.description);
    log.moat(1);
    return log.plusIndent(2);
  },
  startOne: function(spec) {
    if (!isBenchmark(spec)) {
      spec.startTime = now();
    }
    log.moat(1);
    log.gray("- ", spec.description);
    if (isBenchmark(spec)) {
      return log.moat(1);
    }
  },
  finishOne: function(spec) {
    var i, len, message, ref, ref1, stack;
    if (/^(disabled|pending)$/.test(spec.status)) {
      return;
    }
    if (spec.status !== "failed") {
      this.specsPassed += 1;
      return;
    }
    log.moat(1);
    log.plusIndent(2);
    ref = spec.failedExpectations;
    for (i = 0, len = ref.length; i < len; i++) {
      ref1 = ref[i], message = ref1.message, stack = ref1.stack;
      log.red(message);
      log.moat(0);
      log.gray.dim(stack);
      log.moat(1);
    }
    return log.popIndent();
  },
  finishSome: function() {
    return log.popIndent();
  },
  finishAll: function(info) {
    var elapsedTime, specsExecuted, tint;
    specsExecuted = info.totalSpecsExecuted;
    elapsedTime = now() - this.startTime;
    log.moat(1);
    tint = this.specsPassed === specsExecuted ? "green" : "red";
    log[tint](this.specsPassed, " / ", specsExecuted);
    log(" tests passed in ");
    log.pink(elapsedTime, "ms");
    log.moat(1);
    return log.popIndent();
  }
};
